apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-web-api-db-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: prod-web-app
            imageRepo: 533267075370.dkr.ecr.ap-south-1.amazonaws.com/production/web-prod
            imageTag: "2"
            path: web
            targetRevision: main
          - appName: prod-api-app
            imageRepo: 533267075370.dkr.ecr.ap-south-1.amazonaws.com/production/api-prod
            imageTag: "2"
            path: api
            targetRevision: main
          - appName: prod-database
            path: database
            targetRevision: main
          
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd-image-updater.argoproj.io/image-list: "{{appName}}-image={{imageRepo}}:~{{imageTag}}"
        argocd-image-updater.argoproj.io/{{appName}}-image.tag: "~{{imageTag}}"
        argocd-image-updater.argoproj.io/{{appName}}-image.update-strategy: newest-build
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
    spec:
      project: default
      source:
        repoURL: "https://gitlab.com/dumalbhaskar/application-helm-charts.git" 
        targetRevision: "main"
        path: "{{path}}"
        helm:
          parameters:
            - name: "image.repository"
              value: "{{imageRepo}}"
            - name: "image.tag"
              value: "{{imageTag}}"
            - name: "replicaCount"
              value: "1"
      destination:
        server: https://kubernetes.default.svc
        namespace: "prod"
      syncPolicy:
        syncOptions:
         - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
