replicaCount: 1
image:
  repository: 533267075370.dkr.ecr.ap-south-1.amazonaws.com/production/api-prod
  tag: "10"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

env:
  PGDATABASE: "postgres"
  PGUSER: "postgres"
  PGPASSWORD: "postgres"