replicaCount: 1

image:
  repository: 533267075370.dkr.ecr.ap-south-1.amazonaws.com/development/web-dev
  tag: "2"
  pullPolicy: IfNotPresent

service:
  name: web-service
  type: LoadBalancer
  port: 80
  targetPort: 8080

deployment:
  containerPort: 8080
